# -*- coding: utf-8 -*-
"""Welcome to Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

## **1. Loading the data**

> Add blockquote
"""

import pandas as pd

survey = pd.read_excel('survey_responses.xlsx')
fare = pd.read_excel('fare_data.xlsx')

print(survey.shape)
print(survey.head())

print(fare.shape)
print(fare.head())

"""## **2. Cleaning Columns Name**

"""

print(survey.columns.tolist())

"""## **3. Removing duplicates and blanks**

"""

survey.drop_duplicates(inplace=True)
survey.dropna(subset=['q1._which_ride-hailing_app_do_you_use_most_often?'], inplace=True)

fare.drop_duplicates(inplace=True)
fare.dropna(inplace=True)

print(survey.shape)
print(fare.shape)

"""## **4. Saving Cleaned Files**

"""

survey.to_excel('survey_clean.xlsx', index=False)
fare.to_excel('fare_clean.xlsx', index=False)

"""## **5. Survey Analysis**

"""

app_share = survey['q1._which_ride-hailing_app_do_you_use_most_often?'].value_counts(normalize=True) * 100
print(app_share)

satisfaction = survey.groupby('q1._which_ride-hailing_app_do_you_use_most_often?')[['q4a._satisfaction_-_price_(1-5)', 'q4b._satisfaction_-_app_experience_(1-5)', 'q4c._satisfaction_-_driver_quality_(1-5)']].mean().round(2)
print(satisfaction)

switched = survey['q5._have_you_switched_your_main_ride-hailing_app_in_the_last_6_months?'].value_counts()
print(switched)

from collections import Counter
words = ' '.join(survey['q10._any_specific_complaint_about_your_main_app?'].dropna()).lower().split()
print(Counter(words).most_common(15))

import re
from collections import Counter

complaints_list = survey['q10._any_specific_complaint_about_your_main_app?'].dropna().str.lower().str.strip().tolist()

phrase_counts = Counter(complaints_list)
print("Full responses:")
for phrase, count in phrase_counts.most_common(15):
    print(f"{count}x — {phrase}")

"""# **6. Average Fare Per App**



"""

avg_fare = fare.groupby('app')['fare'].mean().round(0)
print(avg_fare)

"""# **7. Surge Frequency Per App**


"""

surge = fare.groupby('app')['surge'].mean() * 100
print(surge)

"""# **8. Average Fare By Route And App**


"""

route_fare = fare.groupby(['route', 'app'])['fare'].mean().round(0)
print(route_fare)

"""# **9. Fare By Time Slots And App**


"""

time_fare = fare.groupby(['time', 'app'])['fare'].mean().round(0)
print(time_fare)

"""# **10. Cheapest App Per Route**


"""

cheapest = fare.groupby(['route', 'app'])['fare'].mean().round(0).reset_index()
cheapest = cheapest.loc[cheapest.groupby('route')['fare'].idxmin()]
print(cheapest)

"""# **11. Creating Database**

"""

import sqlite3

conn = sqlite3.connect('ridehailing.db')
fare.to_sql('fare_data', conn, if_exists='replace', index=False)
survey.to_sql('survey_data', conn, if_exists='replace', index=False)
print("Database created successfully")

"""# **12. Verifying Both Tables Loaded**

"""

print(pd.read_sql_query("SELECT * FROM fare_data LIMIT 5", conn))
print(pd.read_sql_query("SELECT * FROM survey_data LIMIT 5", conn))

"""# **13. Running Queries**

"""

q1 = pd.read_sql_query("SELECT app, ROUND(AVG(fare),0) as avg_fare FROM fare_data GROUP BY app ORDER BY avg_fare", conn)
print("Average Fare by App:")
print(q1)

q2 = pd.read_sql_query("SELECT app, ROUND(100.0*SUM(surge)/COUNT(*),1) as surge_pct FROM fare_data GROUP BY app", conn)
print("\nSurge Rate by App:")
print(q2)

q3 = pd.read_sql_query("SELECT route, app, ROUND(AVG(fare),0) as avg_fare FROM fare_data GROUP BY route, app ORDER BY route, avg_fare", conn)
print("\nAverage Fare by Route and App:")
print(q3)

from google.colab import drive
drive.mount('/content/drive')